<?php

require 'utils.php';


# polymorphism --> poly -->many morphism --> faces

# overloading  in same class
# 2 methods in the same class with the same name
# but different in no of parms, type of parms,
# implementation
generate_title("Overloading");

class Person{

//    function speak()
//    {
//        echo "<h3>I am a person </h3>";
//    }
    function speak($message='')
    {

        echo "<h3>I am a person {$message} </h3>";
    }
}

$person = new Person();
$person->speak();
$person->speak("Hiiiiiiiii");



# overriding



# 2 functions in 2 classes (in inheritance relation)
# function in the parent class do something differs from
# child class


//class

class Employee{
    function speak(){
        echo "I am an Employee";
    }
}

class Manager extends Employee{
        function speak()
        {
            // Call parent function
            parent::speak();
             // TODO: Change the autogenerated stub
            echo "<br>I am the manager";
        }
}

$m = new Manager();
$m->speak();











